font_family CaskaydiaCove Nerd Font Mono
font_size 10

disable_ligatures no
enable_audio_bell no

shell zsh

remember_window_size no
window_padding_width 20

background_opacity 0.50

scrollbar_handle_opacity 
scrollbar_track_opacity 
scrollbar_track_hover_opacity 

confirm_os_window_close 0
sync_to_monitor no

##########
# Colors #
##########

include themes/tokyo-night.conf